### PR TITLE
Add debug impls to text types.

### PR DESCRIPTION
**Pull request by derekdreery**
I'm using the CI to check my code on other platforms.

### CODE REVIEW

**Comment by derekdreery** [comment]
I impl'd `Debug` manually most of the time, because it means that one can change the structs' internals without having the maintenance burden of thinking about `Debug`.

**Comment by derekdreery** [comment]
Hmm, I'll have a go at doing this.

**Review by cmyr — APPROVED** [review]
The third option works for me. :)

**Comment by derekdreery** [comment]
@cmyr I don't have write access on this repo, would you mind merging?

**Comment by cmyr** [comment]
invite sent.

**Pull request merged**
