### PR TITLE
Deduplicate unpremul.

### PR DESCRIPTION
**Pull request by jneem**

### CODE REVIEW

**Review by raphlinus — APPROVED** [review]
Nice cleanup, thanks, and the coregraphics one was missing edge cases. I looked at the [code in Godbolt](https://godbolt.org/z/1Gxh71) and am not super pleased, but I don't think there's much to be done for it besides going to handwritten SIMD intrinsics.

**Comment by jneem** [comment]
Huh, TIL that SSE pre-4.1 didn't have a floor instruction...

By the way, I don't have write access here so I can't merge it myself.

**Comment by cmyr** [comment]
@jneem you should have access?

**Comment by jneem** [comment]
Pretty sure I didn't before, but it looks like I do now?

**Pull request merged**
