### PR TITLE
Github actions for CI

### PR DESCRIPTION
**Pull request by hwchen**

### CODE REVIEW

**Comment by hwchen** [comment]
@cmyr and @raphlinus I've modified `.github/workflows/ci.yml` from druid to work for piet. I believe rustfmt, tests, clippy and doc building are all working (with logic for platform-specific excludes). A scan of the logs appears to look good.

I believe that turning off the azure pipelines integration is a blocker. I've removed the azure configs, but the integration appears to still run.

**Comment by cmyr** [comment]
@hwchen can we keep the azure configs, and we'll just run them both for a week or so?

**Comment by hwchen** [comment]
Sounds good, will do

**Comment by hwchen** [comment]
Should be ready to go?

**Pull request merged**
