### PR TITLE
Change png example to make generative Piet Mondrian artwork.

### PR DESCRIPTION
**Pull request by derekdreery**
temp-image
I felt like we needed more Piet Mondrian-ness in the lib, so I made the example make a composition-style generative artwork. :)

### CODE REVIEW

**Comment by derekdreery** [comment]
I maybe need to use an always-available source of entropy for the Rng.

**Comment by cmyr** [comment]
Aw, I love it. If you want you could just make this unavailable on wasm? I'm not sure exactly what the story is, there...

**Comment by derekdreery** [comment]
Yay I got to remove some conditional compilation code. (Removing code is one of my favourite things)

**Review by cmyr — APPROVED** [review]
This is a lovely addition, thank you!

**Pull request merged**
