### PR TITLE
Switch to github actions for ci

### PR DESCRIPTION
**Pull request by hwchen**

### CODE REVIEW

**Comment by hwchen** [comment]
Odd; #138 works fine. I'm not sure if I have the path wrong, or if it's not working because the PR is from my branch? If I don't figure this out soon, I'll just switch to the other "test-github-actions" PR (which is a branch on `linebender/piet`, started from the `Actions` tab).

**Comment by raphlinus** [comment]
Yeah, I would very easily believe this is because this PR is from your account. There are potential security issues about being able to run actions from random contributors.

**Comment by cmyr** [comment]
try PRing from a branch in this repo? you should be able to push a new branch here if you have commit rights.

**Comment by hwchen** [comment]
Thanks for the insight, I'm going to go with #138 which was "just for testing" but I'll use for real now.

**Comment by hwchen** [comment]
closed in favor of #138

**Pull request closed without merging**
